version: '3'

volumes:
  mongodb_dev: {}
  # node_modules: {}

services: 
  nginx:
    container_name: nginx-node-lb
    build: ./nginx
    ports:
      - '4000:80'
    depends_on: 
      - db
      - nodejs_1
      - nodejs_2
      - nodejs_3

  db:
    image: mongo
    ports: 
      - '27017:27017'
    volumes: 
      - mongodb_dev:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234

  nodejs_1:
    image: shockz/nodetest:0.3
    ports:
      - '3000'
    command: ['./wait-for-it.sh', 'db:27017', '--', 'npm', 'run', 'start:dev']

  nodejs_2:
    image: shockz/nodetest:0.3
    ports:
      - '3000'
    command: ['./wait-for-it.sh', 'db:27017', '--', 'npm', 'run', 'start:dev']

  nodejs_3:
    image: shockz/nodetest:0.3
    ports:
      - '3000'
    command: ['./wait-for-it.sh', 'db:27017', '--', 'npm', 'run', 'start:dev']

    # nodejs:
  #   build:
  #     context: .
  #     dockerfile: ./compose_nodejs/Dockerfile
  #   ports: 
  #     - '3000:3000'
  #   command: ['/wait-for-it.sh', 'db:27017', '--', 'npm', 'run', 'start:dev']
  #   volumes: 
  #     - node_modules:/usr/src/nodetest/node_modules
  #     - .:/usr/src/nodetest